<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWPF>true</UseWPF>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AssemblyName>FUT404DS.Bootstrapper</AssemblyName>
    <RootNamespace>FUT404DS.Bootstrapper</RootNamespace>
    <ApplicationIcon>..\..\FUT404DS\DS4W.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WixToolset.BootstrapperApplicationApi" Version="5.0.2" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="..\..\FUT404DS\DS4W.ico" Link="DS4W.ico" />
    <Compile Include="..\InstallerStartupTaskPolicy.cs" Link="InstallerStartupTaskPolicy.cs" />
    <Compile Include="..\StartupSetupState.cs" Link="StartupSetupState.cs" />
  </ItemGroup>
</Project>
